version: '3.8'

services:
  app:
    build:
      target: dev
    image: ${IMAGE}:${IMAGE_TAG}-dev
    volumes:
      - './.eslint:/app/.eslint'
      - './.jest:/app/.jest'
      - './.stylelint:/app/.stylelint'
      - './build:/app/build'
      - './data:/app/data'
      - './scripts:/app/scripts'
      - './src:/app/src'
      - './static:/app/static'
      - './test:/app/test'
      - './feature-test:/app/feature-test'
