version: '3.8'

services:
  app:
    build:
      target: prod
    environment:
      EXPERIMENT_ENABLED: "false"
    image: ${IMAGE}:${IMAGE_TAG}
    volumes:
      - './.gcp-ncrc-key.json:/var/run/secrets/.gcp-ncrc-key.json'
