apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}--frontend
  labels:
    {{- include "prc.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}--frontend
              servicePort: http
  tls:
    - hosts:
        - {{ .Values.hostname }}
        - www.{{ .Values.hostname }}
      secretName: {{ .Release.Name }}--frontend--letsencrypt-cert
