apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}--frontend
  labels:
    {{- include "prc.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.hostname }}
spec:
  type: LoadBalancer
  ports:
    - targetPort: http
      port: 80
      protocol: TCP
  selector:
    {{- include "prc.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
