version: '3.8'

services:
  app:
    build:
      context: ../
    environment:
      ALLOW_SITE_CRAWLERS: "true"
      APP_ORIGIN: "http://localhost:8080"
      APP_SECRET: "secret"
      CROSSREF_API_BEARER_TOKEN:
      EXPERIMENT_ENABLED: "true"
      GOOGLE_TAG_MANAGER_ID:
      LOG_LEVEL:
      PGUSER: user
      PGHOST: db
      PGPASSWORD: secret
      PGDATABASE: sciety
      TWITTER_API_KEY:
      TWITTER_API_SECRET_KEY:
      TWITTER_API_BEARER_TOKEN:
    ports:
      - '8080:80'
    restart: unless-stopped
  db:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: sciety
    healthcheck:
      test: pg_isready --username $$POSTGRES_USER --dbnam $$POSTGRES_DB || exit 1
      interval: 5s
