name: CI

on:
  push:
    branches:
      - master

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:

  frontend:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker images
        run: |
          make IMAGE_TAG=${IMAGE_TAG} TARGET=prod build
          make IMAGE_TAG=${IMAGE_TAG} TARGET=dev build

      - name: Lint
        run: |
          make IMAGE_TAG=${IMAGE_TAG} lint

      - name: Test
        run: |
          make IMAGE_TAG=${IMAGE_TAG} test

      - name: Push Docker image
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
          docker push liberoadmin/prc-frontend:${IMAGE_TAG}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to staging
        if: github.ref == 'refs/heads/master'
        run: |
          aws --region=us-east-1 eks update-kubeconfig --name libero-eks--franklin
          helm upgrade -i prc--staging \
            --set images.frontend.tag=${IMAGE_TAG} \
            --set hostname=prc-staging.libero.pub \
            --set googleAnalyticsTrackingId=UA-167311475-2 \
            --set disqusApiKey=${DISQUS_API_KEY} \
            --wait \
            helm/prc
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DISQUS_API_KEY: ${{ secrets.DISQUS_API_KEY }}

      - name: Notify Slack
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: prc-general
          status: FAILED
          color: danger
