name: Production

on: 
  push:
    tags:
      - '*'

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:

  frontend:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Deploy to prod
        if: github.ref == 'refs/heads/master'
        run: |
          aws --region=us-east-1 eks update-kubeconfig --name libero-eks--franklin
          helm upgrade -i prc--prod --set images.frontend.tag=${IMAGE_TAG} --set hostname=prc.libero.pub helm/prc
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Notify Slack
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: prc-architecture
          status: FAILED
          color: danger
